### ISSUE TITLE
Why can't my prompt find the. a file below

### ISSUE THREAD

**Issue by mxqgit** [61bcdefg/Hikari-Swift#11]
File cannot be open()ed, errno=2 path=/Library/Developer/Toolchains/Hikari_Swift5.9.2-2024-04-12-a.xctoolchain/usr/lib/clang/15.0.0/lib/darwin/libclang_rt.profile_iossim.a

**Comment by Naville** [comment]
You didn't build device runtime

**Comment by mxqgit** [comment]
I have solved this problem and the compiled toolchain is missing this. a file

**Comment by 61bcdefg** [comment]
just copy it from XcodeDefault.xctoolchain
