### ISSUE TITLE
requires an Xcode default toolchain

### ISSUE THREAD

**Issue by mxqgit** [61bcdefg/Hikari-Swift#13]
Package IPA prompt    App Store distribution requires an Xcode default toolchain

**Comment by 61bcdefg** [comment]
[https://github.com/HikariObfuscator/Hikari/wiki/AppStore-Guideline#setting-up-toolchain-for-appstore](https://github.com/HikariObfuscator/Hikari/wiki/AppStore-Guideline#setting-up-toolchain-for-appstore)
