### ISSUE TITLE
build-toolchain error

### ISSUE THREAD

**Issue by DaemonSong** [61bcdefg/Hikari-Swift#2]
swift-5.8-RELEASE 分支，下载之后调用./swift/utils/build-toolchain Hikari，
报错信息如下：
<img width="1093" alt="image" src="https://github.com/61bcdefg/Hikari-Swift/assets/136695955/51c8bf70-a57e-4290-a758-eaa782d1fd59">

Xcode：14.3.1

clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

swift --version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

cmake --version
cmake version 3.26.1

**Comment by 61bcdefg** [comment]
fixed

**Comment by DaemonSong** [comment]
辛苦再看下，同样的配置信息。报错信息如下：
<img width="1379" alt="image" src="https://github.com/61bcdefg/Hikari-Swift/assets/136695955/f480bebb-23e7-42e1-ae82-c94f5ba8bc2e">

**Comment by 61bcdefg** [comment]
我这里编译遇不到你的问题，不会修

**Comment by Naville** [comment]
这个出错信息就离谱, 不到现场调反正我是盲看看不出来挂哪了

**Comment by DaemonSong** [comment]
看了下报错信息，刚开始是 Linking Swift shared library lib/libllbuildSwift.dylib\nFAILED: lib/libllbuildSwift.dylib ，
不知道这条信息是否有用？ 

大概率是我环境的问题导致的。操作也没有几步，就是下载，然后./swift/utils/build-toolchain执行，一直等待。我换台inter芯片再试一下吧，

如果可以的话，是否能提供一下编译好的工具链？我这边还遇到了OC&Swift混编，存在pch的情况下的编译报错问题(未使用swift版本)，想验证一下swift版本是否还有问题。Thanks,

![image](https://github.com/61bcdefg/Hikari-Swift/assets/136695955/d6e84701-ff1a-46b8-a650-480cdba1db90)

**Comment by DaemonSong** [comment]
使用inter电脑编译成功了，在使用的过程中遇到了其他问题(如截图所示)，请问有什么思路吗？尝试不添加混淆pass依旧报错，也没有找到CLANG_ENABLE_PCH相关的配置项。
在swift源码里面找到了看似相关的https://github.com/apple/swift/pull/20240 以及 https://github.com/apple/swift/pull/60636，去改了一下，还是报错。:)
 所以想着请教一下两位老哥，能否指点迷津。

项目背景：OC&swift混编，支持module化，使用pch文件

<img width="803" alt="image" src="https://github.com/61bcdefg/Hikari-Swift/assets/136695955/117ecab0-3297-49c3-af53-45a0297d50b5">

**Comment by Naville** [comment]
第三方的Clang/LLVM一直不支持Modules

**Comment by DaemonSong** [comment]
> 第三方的Clang/LLVM一直不支持Modules

好家伙，直接把路堵死了...那我再想其他方案吧，一直想着这样搞，
1. 使用原始clang编译出LLVM IR
2. 调用自己的混淆库去混淆LLVM IR
3. 再调用原始clang编译LLVM IR

**Comment by DaemonSong** [comment]
> 第三方的Clang/LLVM一直不支持Modules

很奇怪的是，将Precompile Prefix Header设置为NO，这个问题就不存在了(代价是编译时间拉长N倍)。看样子是预编译的pch缓存路径跟编译使用的module的路径不一致。单独的混编项目，开启module，也是能正常编译的。

**Comment by Naville** [comment]
是, 要修不少东西, 没再往深里研究了。 毕竟这年头CPU核心也不值钱

**Comment by DaemonSong** [comment]
您好，又来请教了...目前使用了Hanabi(https://github.com/61bcdefg/Hanabi)  来使用，编译以后，在项目中build，遇到了这个报错：
Applying Apple Clang Hooks...
: CommandLine Error: Option 'eagerly-invalidate-analyses' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

请教一下，这个在哪里修改...

**Comment by 61bcdefg** [comment]
> 您好，又来请教了...目前使用了Hanabi(https://github.com/61bcdefg/Hanabi)  来使用，编译以后，在项目中build，遇到了这个报错：
> 
> Applying Apple Clang Hooks...
> 
> : CommandLine Error: Option 'eagerly-invalidate-analyses' registered more than once!
> 
> LLVM ERROR: inconsistency in registered CommandLine options
> 
> 
> 
> 请教一下，这个在哪里修改...

你的submodule的branch不对，得用hanabi

**Comment by DaemonSong** [comment]
> > 您好，又来请教了...目前使用了Hanabi(https://github.com/61bcdefg/Hanabi)  来使用，编译以后，在项目中build，遇到了这个报错：
> > Applying Apple Clang Hooks...
> > : CommandLine Error: Option 'eagerly-invalidate-analyses' registered more than once!
> > LLVM ERROR: inconsistency in registered CommandLine options
> > 请教一下，这个在哪里修改...
> 
> 你的submodule的branch不对，得用hanabi

您好，没太明白...主项目我用的https://github.com/61bcdefg/Hikari-Swift 使用的是swift-5.7.2-RELEASE分支，
然后 运行的 git clone https://github.com/61bcdefg/Hanabi.git $(LLVM_SOURCE_PATH)/projects/，
之后在llvm路径下 git submodule update --init --recursive --remote ，最后按照文档的Build进行编译的。
您说的submodule要用hanabi的branch在哪里找？

**Comment by 61bcdefg** [comment]
你得手动把core和header的branch切到hanabi

**Comment by DaemonSong** [comment]
> 你得手动把core和header的branch切到hanabi

感谢，搞定了...
