### ISSUE TITLE
Hanabi, build LLVMHanabi missing target

### ISSUE THREAD

**Issue by alexwillrock** [61bcdefg/Hikari-Swift#6]
你好
感谢您的工作。
很抱歉，我是通过翻译来写这封信的
构建 Hanabi 项目
1) 下载 Hikari swift 5.8 
2) 下载 Hanabi 
git clone https://github.com/61bcdefg/Hanabi.git ~/Desktop/ Hikari/llvm-projects
3) git submodule update --init --recursive --remote
4) 在 llvm-projects 文件夹中执行命令 
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF -DLLVM_ENABLE_PROJECTS="hanabi" -S llvm -B build -G Ninja 
5) 尝试在 ~/Desktop/ Hikari/llvm-projects 文件夹内执行 
ninja LLVMHanabi
错误
ninja: error: unknown target 'LLVMHanabi'

Hi.
Thank you for your work.
I apologize, I'm writing through a translator
I am building a Hanabi project
1) Downloading Hikari swift 5.8 
2) Downloading Hanabi 
git clone https://github.com/61bcdefg/Hanabi.git ~/Desktop/ Hikari/llvm-projects
3) git submodule update --init --recursive --remote
4) in the llvm-projects folder I execute the command 
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF -DLLVM_ENABLE_PROJECTS="hanabi" -S llvm -B build -G Ninja 
5) Trying to execute inside the ~/Desktop/ Hikari/llvm-projects folder 
ninja LLVMHanabi
error
ninja: error: unknown target 'LLVMHanabi'

**Comment by Naville** [comment]
I think the Hanabi module folder must be placed in LLVM/tools/ for cmake to detect it

**Comment by alexwillrock** [comment]
thanks a lot) you save my day
I move Hanabi into /llvm-project/llvm/tools and add Hanabi folder into /llvm-project/llvm/tools/CMakeLists.txt 
`add_llvm_tool_subdirectory(Hanabi)`
