### ISSUE TITLE
Swift 5.9?

### ISSUE THREAD

**Issue by sourcelocation** [61bcdefg/Hikari-Swift#7]
Hi, thanks for maintaining this repository. Do you think updating it to Swift 5.9 is possible?

**Comment by Naville** [comment]
Possible, yes.
Someone willing to actually do it? No

**Comment by sourcelocation** [comment]
> Possible, yes.
> 
> Someone willing to actually do it? No

Got it. Can you recommend other obfuscation methods which work with the latest Swift + Xcode combo?

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-Swift/tree/swift-5.9.2-RELEASE](https://github.com/61bcdefg/Hikari-Swift/tree/swift-5.9.2-RELEASE)
