### ISSUE TITLE
感谢大神，请问这样的混淆方式，对cocos2d 打包出来的xcode工程能起到混淆作用吗？

### ISSUE THREAD

**Issue by testpangbb** [61bcdefg/Hikari-Swift#8]
xcode被自动升级到了15.2，swift版本为最新的5.9，无法使用这个来编译。
请问这种方式是不是只能混淆原生的OC和swfit代码，而无法混淆游戏工程包打包出来的xcode代码。谢谢。

xcode was automatically upgraded to 15.2, swift is the latest version 5.9, and cannot be compiled using this.
May I ask if this method can only confuse the native OC and swfit code, but can not confuse the xcode code packaged out of the game engineering package. thank you.

**Comment by testpangbb** [comment]
I'm willing to pay for it if possible

**Comment by Naville** [comment]
> 无法使用这个来编译。

具体什么现象

**Comment by testpangbb** [comment]
FAILED: bootstrapping1/SwiftCompilerSources/Basic.o /Users/pangqian/Downloads/Hikari-Swift/build/Ninja-Release/swift-macosx-x86_64/bootstrapping1/SwiftCompilerSources/Basic.o 

failed to build module 'CoreFoundation'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.9.2 (swiftlang-5.9.2.2.11 clang-1500.1.0.2.2)', while this compiler is 'Apple Swift version 5.8 (swift-5.8-RELEASE)'). Please select a toolchain which matches the SDK.

开始出现第一个  后面出现第二个错误。 
git clone --recurse-submodules -b swift-5.8-RELEASE https://github.com/61bcdefg/Hikari-Swift.git ~/Downloads/Hikari-Swift
到了 百分之90多就不行了

**Comment by Naville** [comment]
那么为什么不能切换回老版本Xcode

**Comment by testpangbb** [comment]
老版本xcode我安装了14.2，也下载了swift5.8，但是这个编译我不知道如何去修改路径让他找到14.2去编译
或者不知道怎么让他去找到swift5.8去编译

**Comment by Naville** [comment]
自己研究构建脚本
